// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/4/2025, 4:49:15 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/tsaotingwei/Documents/GitHub/koafaith/Frontend/TCG/codefest.taipei/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tsaotingwei/Documents/GitHub/koafaith/Frontend/TCG/codefest.taipei/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tsaotingwei/Documents/GitHub/koafaith/Frontend/TCG/codefest.taipei/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tsaotingwei/Documents/GitHub/koafaith/Frontend/TCG/codefest.taipei/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tsaotingwei/Documents/GitHub/koafaith/Frontend/TCG/codefest.taipei/plugins/**/*.{js,ts,mjs}","/Users/tsaotingwei/Documents/GitHub/koafaith/Frontend/TCG/codefest.taipei/composables/**/*.{js,ts,mjs}","/Users/tsaotingwei/Documents/GitHub/koafaith/Frontend/TCG/codefest.taipei/utils/**/*.{js,ts,mjs}","/Users/tsaotingwei/Documents/GitHub/koafaith/Frontend/TCG/codefest.taipei/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tsaotingwei/Documents/GitHub/koafaith/Frontend/TCG/codefest.taipei/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/tsaotingwei/Documents/GitHub/koafaith/Frontend/TCG/codefest.taipei/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/tsaotingwei/Documents/GitHub/koafaith/Frontend/TCG/codefest.taipei/app.config.{js,ts,mjs}","/Users/tsaotingwei/Documents/GitHub/koafaith/Frontend/TCG/codefest.taipei/app/spa-loading-template.html"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;